---
  title: "GRIN Model"
  author: Elizabeth Pansing
output: html_notebook
---
  
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
library(dplyr)
library(popbio)
library(tidyr)

source("/Users/elizabethpansing/Documents/Test/Field-et-al.-Model/WBP Demographic Model/GRIN parameter estimates.R")

```


```{r}

n <- c(0, 0, 1000, 0, 0, 0)
names(n) <- c("SEED1", "SEED2", "CS", "SD", "SAP", "MA")


#define variables


survival_SEED1    <- function(size){  # mortality rate of seeds
  rbeta(n = size, 
        shape1 = SEED1_survive_alpha, 
        shape2 = SEED1_survive_beta)
} # draws randomly from a beta distribution where seeds either die because of seed pilferage (assuming that all pilfered seeds are lost to reproduction), germinate, or persist in a soil seed bank. 



survival_CS     <- function(size){
  rbeta(n = size, 
        shape1 = CS_survive_alpha,
        shape2 = CS_survive_beta)
}


survival_SD     <- function(size){  # mortality rate of seedlings
  rbeta(n = size,
        shape1 = SD_survive_alpha,
        shape2 = SD_survive_beta)
}


survival_SAP     <- function(){  # mortality rate of saplings
  return(0.8)
}

survival_RMA     <- function(){  # mortality rate of reproductively mature adults
  0.99  #changed from 1 proposed in GRIN proposal bc immortality seemed a bit too idealistic??
}


survival_vector <- function(size){   #survival vector
  c(survival_SD(size = size),
    survival_SAP(),
    survival_RMA())
}

survival_vector(size = 1)

# Germination 

germ_SEED1 <- function(size){
  rbeta(n = size, 
        shape1 = SEED1_germ_alpha,
        shape2 = SEED1_germ_beta)
}

germ_SEED2 <- function(size){
  rbeta(n = size, 
        shape1 = SEED2_germ_alpha,
        shape2 = SEED2_germ_beta)
}


# Residence time

residence_SD   <- function(x){   # # years as seedling (SD)
  return(30) 
}

residence_SAP  <- function(x){   # # years as sapling (SAP)
  return(30) 
}   

residence_RMA  <- function(x){   # # years as reproductively mature
  return(Inf)
}



residence_vector <- function(x){
  c(residence_SD(),
    residence_SAP(),
    residence_RMA())
}

residence_vector()


# Fertility

No_caches <- function(t, size){
  result <- NULL
      
    for(i in 1:size){
      value <- ((12.5*cos(1.5 * t) + 14 + rnorm(1, sd = 3.5)) * 45)/ 3
      if( value >= 0){
        result[i] <- value
        } else if(value < 0){
        result[i] <- value - value
        }
    }
 return(result) 
} # 45 seeds/cone with an average of 3 seeds per cache. 45% of the seeds are not retreived by CN

```


```{r}
si <- function(size){
  (1 - (1/residence_vector())) *
    survival_vector(size = size)
}

ti <- function(size) {
  (1/residence_vector()) * 
    survival_vector(size = size)
}


S <- function(t){
  matrix(c(               0,              0,             0,        0,         0, No_caches(t,1) *si(1)[3],
                          survival_SEED1(1),             0,             0,        0,         0,        0,
                          germ_SEED1(1), germ_SEED2(1),             0,        0,         0,        0,
                          0,              0, survival_CS(1), si(1)[1],        0,        0,
                          0,              0,             0,  ti(1)[1], si(1)[2],        0,
                          0,              0,             0,        0,  ti(1)[2], si(1)[3]),
         byrow = T, nrow = 6, 
         dimnames = list(c("SEED1", "SEED2", "CS", "SD", "SAP", "MA"),
                         c("SEED1", "SEED2", "CS", "SD", "SAP", "MA"))) 
}

t <- 1
S(t) 
```


```{r}
library(plyr)

n <- c(62, 580 + 38, 79, 65, 91,  353) #Arbitrary starting pop size vectors
n1 <- c(500, 0, 0, 0, 0,  0)


project <- function(projection_time, n0, reps = 100){    # stochastic projection function that tracks stage based pop sizes over time for each simulation
  
  results <- stochastic_matrixes <-   #Create null matrix that will hold stage
  array(0, dim = c(projection_time, length(n0) + 1, reps)) #based population sizes
  
  for(j in 1:reps){     # Iterate through i years of population growth j times
    
     if(j == 1){           #Create null vectors that will hold fire intervals for each iteration
    intervals <- NULL
    iteration <- NULL
  } else if(j != 1){
    intervals <- intervals
    iteration <- iteration
  }
    
    interval <- rgamma(4, shape = fire_alpha, rate = fire_beta)  %>% 
      round(., 0) %>% 
      cumsum(.)       # Select fire years from a gamma distribution
    interval <- interval[-which(interval > projection_time)]  #trim to only include those within the projection time
  
    intervals <- append(intervals, interval, after = length(intervals))
    
    iteration <- append(iteration, rep(j, length(interval)), 
                        after = length(iteration))
    
  
    pops <- matrix(0, nrow = projection_time , ncol = length(n)) 
    
    for(i in 1:projection_time){  #get population
      t <-  i #time counter
      tSinceFire <- ifelse(i == 1, 1, tSinceFire)
      fire <- ifelse(t %in% interval, TRUE, FALSE)  # Determine whether this iteration experiences a stand replacing fire
      
      
      if(fire == T){               # Update time since fire counter
        
        tSinceFire <- 1 
        pops[i,] <- c(0, 0, 0, 0, 0, 0)    # Assuming stand replacing burn with no survival and no regeneration. Most fires go out with first snow. e.g., Romme 1982
        n <- pops[i,]
        
      } else if(fire == F & tSinceFire == 2 & t != 2){
        tSinceFire <- tSinceFire + 1
        pops[i,] <- c(No_caches(size = 1, t = t), 0, 0, 0, 0, 0)
        n <- pops[i,]
      
      } else if(fire == F & tSinceFire == 2 & t == 2){
        tSinceFire <- tSinceFire + 1
        
        mat <- S(t = t)
        pops[i,] <- t(mat %*% as.matrix(n, nrow = length(n), ncol = 1))
        n <- as.matrix(pops[i,], nrow = length(pops[i,]), ncol = 1)
      
      } else if(fire == F & tSinceFire != 2){
        tSinceFire <- tSinceFire + 1
        
        mat <- S(t = t)
        pops[i,] <- t(mat %*% as.matrix(n, nrow = length(n), ncol = 1))
        n <- as.matrix(pops[i,], nrow = length(pops[i,]), ncol = 1)
      }
        
      # } else if(fire == T)
      #   
      #   pops[,i] <- c(0,0,0,0,0,0)
      # 
      # } else if(tSinceFire == 1){   # e.g., Romme 1982
      #   pops[i,] <- c(No_caches(1), 0, 0, 0, 0, 0)
      #   
      #   } else if(fire == F) {
      #   mat <- S(t = t)
      #   pops[i,] <- t(mat %*% as.matrix(n, nrow = length(n), ncol = 1))
      #   n <- as.matrix(pops[i,], nrow = length(pops[i,]), ncol = 1)
      # }
      
    }
    
    pops <- cbind(pops, rep(1:projection_time))
    
    
    results[, ,j] <- pops
    
  }
  
  pop_sizes <- plyr::adply(results, 3)
  colnames(pop_sizes) <- c("Iteration", "SEED1", "SEED2", "CS", "SD", "SAP", "MA", "t")
  
  fire_intervals <- cbind(iteration, intervals)
  
  results <- list(pop_sizes = pop_sizes, fire_intervals = fire_intervals)
  
  return(results)
}



projection <- project(projection_time = 500, n0 = n, reps = 50) 

projection <- gather(projection20$pop_sizes, Stage, Count, -Iteration, -t) %>%
  filter(., !Stage == "SEED1") %>%
  filter(., !Stage == "SEED2") %>%
  group_by(., Iteration, t) %>%
  summarise_at(., vars(Count), funs(sum)) %>%
  ungroup(.)


ggplot(data = projection, aes(x = t, y = Count, col = Iteration)) +
  geom_line() +
  theme(legend.position="none")

hist(projection$Count[projection$t == 500], breaks = 100)

```




```{r}
reps <- 10000

stochastic_matrixes <- array(0, dim = c(6,6,reps))



for(i in 1:reps){
  stochastic_matrixes[, , i] <- S(i)
}



A <- list(NULL)

for(i in 1:reps){
  mat <- stochastic_matrixes[,,i]
  A[[i]] <- mat
}

rm(stochastic_matrixes)

stoch.sens(A, tlimit = 500)

sgr <- stoch.growth.rate(A)
exp(sgr$approx)

```

